// Blog articles — stored as static content
// Each article targets long-tail keywords for SEO

export const articles = [
  {
    slug: 'signs-you-should-see-a-dermatologist',
    title: '10 Signs You Should See a Dermatologist',
    description: 'Persistent acne, unusual moles, sudden hair loss? Learn the warning signs that mean you need a dermatologist consultation.',
    specialization: 'Dermatologist',
    publishedDate: '2026-08-01',
    readTime: '5 min',
    image: '🧴',
    content: [
      { type: 'intro', text: 'Your skin is your body\'s largest organ, and changes in it can signal underlying health issues. While minor skin concerns often resolve on their own, certain symptoms require professional attention. Here are 10 signs you should consult a dermatologist.' },
      { type: 'heading', text: '1. Persistent Acne That Won\'t Clear' },
      { type: 'paragraph', text: 'If over-the-counter products haven\'t helped after 2-3 months, a dermatologist can prescribe stronger treatments like retinoids, antibiotics, or hormonal therapy. Severe acne left untreated can cause permanent scarring.' },
      { type: 'heading', text: '2. Sudden or Excessive Hair Loss' },
      { type: 'paragraph', text: 'Losing 50-100 hairs daily is normal. But if you notice thinning patches, bald spots, or excessive shedding, it could indicate alopecia, thyroid issues, or nutritional deficiencies. Early treatment gives the best results.' },
      { type: 'heading', text: '3. A Mole That Changes Shape or Color' },
      { type: 'paragraph', text: 'Use the ABCDE rule: Asymmetry, Border irregularity, Color changes, Diameter larger than 6mm, or Evolving appearance. Any of these warrant immediate consultation to rule out skin cancer.' },
      { type: 'heading', text: '4. Rashes That Don\'t Go Away' },
      { type: 'paragraph', text: 'A rash lasting more than 2 weeks, spreading, or accompanied by fever needs medical attention. It could be eczema, psoriasis, fungal infection, or an allergic reaction.' },
      { type: 'heading', text: '5. Severe Itching Without Visible Cause' },
      { type: 'paragraph', text: 'Chronic itching (pruritus) without a rash can indicate liver problems, kidney disease, or internal conditions. A dermatologist can run tests to identify the cause.' },
      { type: 'heading', text: '6. Skin Infections That Keep Returning' },
      { type: 'paragraph', text: 'Recurring boils, fungal infections, or cold sores suggest an underlying immune issue. Professional treatment breaks the cycle of recurrence.' },
      { type: 'heading', text: '7. Excessive Sweating (Hyperhidrosis)' },
      { type: 'paragraph', text: 'If you sweat excessively even in cool conditions, prescription antiperspirants, Botox injections, or other treatments can help significantly.' },
      { type: 'heading', text: '8. Nail Changes' },
      { type: 'paragraph', text: 'Discoloration, thickening, or separation of nails can indicate fungal infections, psoriasis, or nutritional deficiencies. Don\'t ignore persistent nail problems.' },
      { type: 'heading', text: '9. Dark Patches or Pigmentation' },
      { type: 'paragraph', text: 'Melasma, dark circles, or uneven skin tone can be treated effectively with professional chemical peels, laser therapy, or topical prescriptions.' },
      { type: 'heading', text: '10. Chronic Dandruff or Scalp Issues' },
      { type: 'paragraph', text: 'Persistent dandruff that doesn\'t respond to medicated shampoos may be seborrheic dermatitis or scalp psoriasis, requiring prescription treatment.' },
      { type: 'heading', text: 'When to Book a Consultation' },
      { type: 'paragraph', text: 'Don\'t wait for skin problems to worsen. Early diagnosis and treatment prevents scarring, spreading, and complications. Most skin conditions are highly treatable when caught early.' },
    ]
  },
  {
    slug: 'when-to-visit-a-gynaecologist',
    title: 'When to Visit a Gynaecologist — Complete Guide',
    description: 'Irregular periods, pelvic pain, pregnancy planning? Know when you should consult a gynaecologist and what to expect during your visit.',
    specialization: 'Gynaecologist',
    publishedDate: '2026-08-02',
    readTime: '6 min',
    image: '🤰',
    content: [
      { type: 'intro', text: 'Many women delay gynaecologist visits due to embarrassment or uncertainty about when it\'s necessary. Regular check-ups and timely consultations are crucial for reproductive health. Here\'s your complete guide.' },
      { type: 'heading', text: 'You Should Visit a Gynaecologist If You Have:' },
      { type: 'paragraph', text: '• Irregular, heavy, or painful periods\n• Missed periods (when not pregnant)\n• Unusual vaginal discharge or odor\n• Pelvic pain or pressure\n• Pain during intercourse\n• Planning pregnancy or need contraception advice\n• Reached age 21 (routine screening recommended)' },
      { type: 'heading', text: 'Common Conditions a Gynaecologist Treats' },
      { type: 'paragraph', text: 'PCOD/PCOS is one of the most common conditions affecting Indian women, causing irregular periods, weight gain, acne, and fertility issues. Early management with lifestyle changes and medication can prevent complications.' },
      { type: 'paragraph', text: 'Endometriosis affects 1 in 10 women and causes severe period pain, heavy bleeding, and fertility problems. Many women suffer for years before diagnosis — don\'t normalize extreme pain.' },
      { type: 'paragraph', text: 'Fibroids are non-cancerous growths in the uterus that can cause heavy periods, pelvic pressure, and frequent urination. Treatment ranges from medication to minimally invasive procedures.' },
      { type: 'heading', text: 'Pregnancy and Prenatal Care' },
      { type: 'paragraph', text: 'If you\'re planning pregnancy, a pre-conception visit helps identify and address any issues beforehand. Once pregnant, regular antenatal visits monitor both mother and baby\'s health.' },
      { type: 'heading', text: 'What to Expect During Your Visit' },
      { type: 'paragraph', text: 'A typical visit includes discussion of your symptoms, medical history, and possibly a physical examination. Many concerns can be addressed through consultation alone — not every visit requires an examination.' },
      { type: 'heading', text: 'Can You Consult Online?' },
      { type: 'paragraph', text: 'Yes! Many gynaecological concerns — period problems, PCOD management, contraception advice, pregnancy queries — can be effectively addressed through video consultation. Physical examination is only needed for specific cases.' },
    ]
  },
  {
    slug: 'heart-attack-warning-signs',
    title: 'Heart Attack Warning Signs — When to See a Cardiologist',
    description: 'Chest pain, breathlessness, high BP? Learn the warning signs of heart disease and when you should consult a cardiologist immediately.',
    specialization: 'Cardiologist',
    publishedDate: '2026-08-03',
    readTime: '5 min',
    image: '❤️',
    content: [
      { type: 'intro', text: 'Heart disease is the #1 killer in India, causing over 25% of all deaths. Many heart attacks happen to people who ignored warning signs for months. Know when to see a cardiologist — it could save your life.' },
      { type: 'heading', text: 'Emergency Signs — Go to Hospital Immediately' },
      { type: 'paragraph', text: '• Crushing chest pain or pressure lasting more than 5 minutes\n• Pain spreading to left arm, jaw, neck, or back\n• Severe breathlessness with sweating\n• Sudden dizziness or fainting\n• Nausea with chest discomfort\n\nCall an ambulance immediately. Do NOT drive yourself.' },
      { type: 'heading', text: 'Warning Signs — Book a Cardiologist Appointment' },
      { type: 'paragraph', text: '• Blood pressure consistently above 140/90\n• Chest pain or tightness during physical activity\n• Shortness of breath climbing stairs\n• Irregular heartbeat or palpitations\n• Swelling in legs, ankles, or feet\n• Unexplained fatigue\n• Family history of heart disease' },
      { type: 'heading', text: 'Risk Factors You Can Control' },
      { type: 'paragraph', text: 'High blood pressure, diabetes, smoking, obesity, lack of exercise, high cholesterol, and stress all increase heart disease risk. A cardiologist can create a prevention plan tailored to your risk factors.' },
      { type: 'heading', text: 'Tests a Cardiologist May Recommend' },
      { type: 'paragraph', text: 'ECG (electrocardiogram), echocardiogram, stress test, lipid profile, and cardiac CT scan help assess heart health. Many are non-invasive and quick.' },
      { type: 'heading', text: 'Prevention is Better Than Cure' },
      { type: 'paragraph', text: 'If you\'re over 35, have diabetes or high BP, or have a family history of heart disease — schedule a preventive cardiologist consultation. Early intervention saves lives.' },
    ]
  },
  {
    slug: 'child-sick-when-to-see-pediatrician',
    title: 'Is Your Child Sick? When to Take Them to a Pediatrician',
    description: 'Fever, cough, rashes in children — know when home remedies are enough and when you need a pediatrician consultation.',
    specialization: 'Pediatrician',
    publishedDate: '2026-08-04',
    readTime: '5 min',
    image: '👶',
    content: [
      { type: 'intro', text: 'Every parent worries when their child falls sick. While most childhood illnesses are minor and resolve on their own, certain signs indicate you should consult a pediatrician promptly. Here\'s your guide to knowing the difference.' },
      { type: 'heading', text: 'See a Pediatrician Immediately If Your Child Has:' },
      { type: 'paragraph', text: '• Fever above 102°F (39°C) lasting more than 2 days\n• Difficulty breathing or rapid breathing\n• Refusing to eat or drink for more than 12 hours\n• Severe vomiting or diarrhea (risk of dehydration)\n• Rash that doesn\'t fade when pressed\n• Unusual drowsiness or difficulty waking\n• Seizures or convulsions' },
      { type: 'heading', text: 'Common Childhood Illnesses That Need a Doctor' },
      { type: 'paragraph', text: 'Ear infections (pulling at ears, crying), urinary tract infections (pain during urination, fever), and respiratory infections (persistent cough, wheezing) all need professional treatment — home remedies aren\'t enough.' },
      { type: 'heading', text: 'Routine Pediatrician Visits' },
      { type: 'paragraph', text: 'Even when your child is healthy, regular check-ups are important:\n• Monthly for first year\n• Every 3 months (ages 1-3)\n• Every 6 months (ages 3-6)\n• Annually after age 6\n\nThese visits track growth, development milestones, and vaccinations.' },
      { type: 'heading', text: 'Vaccination Schedule' },
      { type: 'paragraph', text: 'Following India\'s National Immunization Schedule protects your child from serious diseases. Missed a vaccine? A pediatrician can create a catch-up schedule.' },
      { type: 'heading', text: 'Online Pediatric Consultation' },
      { type: 'paragraph', text: 'For non-emergency concerns — mild fever, feeding issues, minor rashes, behavioral questions — video consultation with a pediatrician is convenient and effective. You get professional advice without exposing a sick child to more germs in a waiting room.' },
    ]
  },
  {
    slug: 'mental-health-when-to-get-help',
    title: 'Mental Health: 7 Signs You Need Professional Help',
    description: 'Depression, anxiety, insomnia — when should you see a psychiatrist? Learn the signs that indicate you need professional mental health support.',
    specialization: 'Psychiatrist',
    publishedDate: '2026-08-05',
    readTime: '5 min',
    image: '🧠',
    content: [
      { type: 'intro', text: 'Mental health is as important as physical health, yet most Indians hesitate to seek help. There\'s no shame in consulting a psychiatrist — it\'s a sign of strength, not weakness. Here are 7 signs you should reach out.' },
      { type: 'heading', text: '1. Persistent Sadness or Hopelessness' },
      { type: 'paragraph', text: 'Feeling sad for more than 2 weeks, losing interest in activities you once enjoyed, or feeling empty and hopeless are classic signs of depression. It\'s a medical condition, not a character flaw — and it\'s treatable.' },
      { type: 'heading', text: '2. Overwhelming Anxiety or Worry' },
      { type: 'paragraph', text: 'If worry dominates your daily life, causes physical symptoms (racing heart, sweating, nausea), or prevents you from normal activities, professional help can make a dramatic difference.' },
      { type: 'heading', text: '3. Sleep Problems' },
      { type: 'paragraph', text: 'Chronic insomnia (can\'t fall asleep) or hypersomnia (sleeping too much) lasting more than 3 weeks often indicates an underlying mental health condition that needs treatment.' },
      { type: 'heading', text: '4. Panic Attacks' },
      { type: 'paragraph', text: 'Sudden episodes of intense fear with physical symptoms — chest pain, difficulty breathing, dizziness, trembling — are panic attacks. They\'re terrifying but highly treatable with the right approach.' },
      { type: 'heading', text: '5. Relationship or Work Problems' },
      { type: 'paragraph', text: 'When mental health issues start affecting your relationships, work performance, or daily functioning, it\'s time to seek help before things deteriorate further.' },
      { type: 'heading', text: '6. Substance Use to Cope' },
      { type: 'paragraph', text: 'Using alcohol, drugs, or medications to manage stress, anxiety, or emotional pain is a warning sign. A psychiatrist can address the root cause and provide healthier coping strategies.' },
      { type: 'heading', text: '7. Thoughts of Self-Harm' },
      { type: 'paragraph', text: 'If you\'re having thoughts of hurting yourself or ending your life, please reach out immediately. Call a helpline (Vandrevala Foundation: 1860-2662-345) or consult a psychiatrist urgently. Help is available.' },
      { type: 'heading', text: 'Online Mental Health Consultation' },
      { type: 'paragraph', text: 'Mental health consultations are particularly effective online — you can speak from the privacy of your home, without the stigma of visiting a clinic. Video calls offer the same quality of care as in-person visits for therapy and medication management.' },
    ]
  }
];
