// Blog articles — stored as static content
// Each article targets long-tail keywords for SEO

export const articles = [
  {
    slug: 'signs-you-should-see-a-dermatologist',
    title: '10 Signs You Should See a Dermatologist',
    description: 'Persistent acne, unusual moles, sudden hair loss? Learn the warning signs that mean you need a dermatologist consultation.',
    specialization: 'Dermatologist',
    publishedDate: '2026-08-01',
    readTime: '5 min',
    image: '🧴',
    content: [
      { type: 'intro', text: 'Your skin is your body\'s largest organ, and changes in it can signal underlying health issues. While minor skin concerns often resolve on their own, certain symptoms require professional attention. Here are 10 signs you should consult a dermatologist.' },
      { type: 'heading', text: '1. Persistent Acne That Won\'t Clear' },
      { type: 'paragraph', text: 'If over-the-counter products haven\'t helped after 2-3 months, a dermatologist can prescribe stronger treatments like retinoids, antibiotics, or hormonal therapy. Severe acne left untreated can cause permanent scarring.' },
      { type: 'heading', text: '2. Sudden or Excessive Hair Loss' },
      { type: 'paragraph', text: 'Losing 50-100 hairs daily is normal. But if you notice thinning patches, bald spots, or excessive shedding, it could indicate alopecia, thyroid issues, or nutritional deficiencies. Early treatment gives the best results.' },
      { type: 'heading', text: '3. A Mole That Changes Shape or Color' },
      { type: 'paragraph', text: 'Use the ABCDE rule: Asymmetry, Border irregularity, Color changes, Diameter larger than 6mm, or Evolving appearance. Any of these warrant immediate consultation to rule out skin cancer.' },
      { type: 'heading', text: '4. Rashes That Don\'t Go Away' },
      { type: 'paragraph', text: 'A rash lasting more than 2 weeks, spreading, or accompanied by fever needs medical attention. It could be eczema, psoriasis, fungal infection, or an allergic reaction.' },
      { type: 'heading', text: '5. Severe Itching Without Visible Cause' },
      { type: 'paragraph', text: 'Chronic itching (pruritus) without a rash can indicate liver problems, kidney disease, or internal conditions. A dermatologist can run tests to identify the cause.' },
      { type: 'heading', text: '6. Skin Infections That Keep Returning' },
      { type: 'paragraph', text: 'Recurring boils, fungal infections, or cold sores suggest an underlying immune issue. Professional treatment breaks the cycle of recurrence.' },
      { type: 'heading', text: '7. Excessive Sweating (Hyperhidrosis)' },
      { type: 'paragraph', text: 'If you sweat excessively even in cool conditions, prescription antiperspirants, Botox injections, or other treatments can help significantly.' },
      { type: 'heading', text: '8. Nail Changes' },
      { type: 'paragraph', text: 'Discoloration, thickening, or separation of nails can indicate fungal infections, psoriasis, or nutritional deficiencies. Don\'t ignore persistent nail problems.' },
      { type: 'heading', text: '9. Dark Patches or Pigmentation' },
      { type: 'paragraph', text: 'Melasma, dark circles, or uneven skin tone can be treated effectively with professional chemical peels, laser therapy, or topical prescriptions.' },
      { type: 'heading', text: '10. Chronic Dandruff or Scalp Issues' },
      { type: 'paragraph', text: 'Persistent dandruff that doesn\'t respond to medicated shampoos may be seborrheic dermatitis or scalp psoriasis, requiring prescription treatment.' },
      { type: 'heading', text: 'When to Book a Consultation' },
      { type: 'paragraph', text: 'Don\'t wait for skin problems to worsen. Early diagnosis and treatment prevents scarring, spreading, and complications. Most skin conditions are highly treatable when caught early.' },
    ]
  },
  {
    slug: 'when-to-visit-a-gynaecologist',
    title: 'When to Visit a Gynaecologist — Complete Guide',
    description: 'Irregular periods, pelvic pain, pregnancy planning? Know when you should consult a gynaecologist and what to expect during your visit.',
    specialization: 'Gynaecologist',
    publishedDate: '2026-08-02',
    readTime: '6 min',
    image: '🤰',
    content: [
      { type: 'intro', text: 'Many women delay gynaecologist visits due to embarrassment or uncertainty about when it\'s necessary. Regular check-ups and timely consultations are crucial for reproductive health. Here\'s your complete guide.' },
      { type: 'heading', text: 'You Should Visit a Gynaecologist If You Have:' },
      { type: 'paragraph', text: '• Irregular, heavy, or painful periods\n• Missed periods (when not pregnant)\n• Unusual vaginal discharge or odor\n• Pelvic pain or pressure\n• Pain during intercourse\n• Planning pregnancy or need contraception advice\n• Reached age 21 (routine screening recommended)' },
      { type: 'heading', text: 'Common Conditions a Gynaecologist Treats' },
      { type: 'paragraph', text: 'PCOD/PCOS is one of the most common conditions affecting Indian women, causing irregular periods, weight gain, acne, and fertility issues. Early management with lifestyle changes and medication can prevent complications.' },
      { type: 'paragraph', text: 'Endometriosis affects 1 in 10 women and causes severe period pain, heavy bleeding, and fertility problems. Many women suffer for years before diagnosis — don\'t normalize extreme pain.' },
      { type: 'paragraph', text: 'Fibroids are non-cancerous growths in the uterus that can cause heavy periods, pelvic pressure, and frequent urination. Treatment ranges from medication to minimally invasive procedures.' },
      { type: 'heading', text: 'Pregnancy and Prenatal Care' },
      { type: 'paragraph', text: 'If you\'re planning pregnancy, a pre-conception visit helps identify and address any issues beforehand. Once pregnant, regular antenatal visits monitor both mother and baby\'s health.' },
      { type: 'heading', text: 'What to Expect During Your Visit' },
      { type: 'paragraph', text: 'A typical visit includes discussion of your symptoms, medical history, and possibly a physical examination. Many concerns can be addressed through consultation alone — not every visit requires an examination.' },
      { type: 'heading', text: 'Can You Consult Online?' },
      { type: 'paragraph', text: 'Yes! Many gynaecological concerns — period problems, PCOD management, contraception advice, pregnancy queries — can be effectively addressed through video consultation. Physical examination is only needed for specific cases.' },
    ]
  },
  {
    slug: 'heart-attack-warning-signs',
    title: 'Heart Attack Warning Signs — When to See a Cardiologist',
    description: 'Chest pain, breathlessness, high BP? Learn the warning signs of heart disease and when you should consult a cardiologist immediately.',
    specialization: 'Cardiologist',
    publishedDate: '2026-08-03',
    readTime: '5 min',
    image: '❤️',
    content: [
      { type: 'intro', text: 'Heart disease is the #1 killer in India, causing over 25% of all deaths. Many heart attacks happen to people who ignored warning signs for months. Know when to see a cardiologist — it could save your life.' },
      { type: 'heading', text: 'Emergency Signs — Go to Hospital Immediately' },
      { type: 'paragraph', text: '• Crushing chest pain or pressure lasting more than 5 minutes\n• Pain spreading to left arm, jaw, neck, or back\n• Severe breathlessness with sweating\n• Sudden dizziness or fainting\n• Nausea with chest discomfort\n\nCall an ambulance immediately. Do NOT drive yourself.' },
      { type: 'heading', text: 'Warning Signs — Book a Cardiologist Appointment' },
      { type: 'paragraph', text: '• Blood pressure consistently above 140/90\n• Chest pain or tightness during physical activity\n• Shortness of breath climbing stairs\n• Irregular heartbeat or palpitations\n• Swelling in legs, ankles, or feet\n• Unexplained fatigue\n• Family history of heart disease' },
      { type: 'heading', text: 'Risk Factors You Can Control' },
      { type: 'paragraph', text: 'High blood pressure, diabetes, smoking, obesity, lack of exercise, high cholesterol, and stress all increase heart disease risk. A cardiologist can create a prevention plan tailored to your risk factors.' },
      { type: 'heading', text: 'Tests a Cardiologist May Recommend' },
      { type: 'paragraph', text: 'ECG (electrocardiogram), echocardiogram, stress test, lipid profile, and cardiac CT scan help assess heart health. Many are non-invasive and quick.' },
      { type: 'heading', text: 'Prevention is Better Than Cure' },
      { type: 'paragraph', text: 'If you\'re over 35, have diabetes or high BP, or have a family history of heart disease — schedule a preventive cardiologist consultation. Early intervention saves lives.' },
    ]
  },
  {
    slug: 'child-sick-when-to-see-pediatrician',
    title: 'Is Your Child Sick? When to Take Them to a Pediatrician',
    description: 'Fever, cough, rashes in children — know when home remedies are enough and when you need a pediatrician consultation.',
    specialization: 'Pediatrician',
    publishedDate: '2026-08-04',
    readTime: '5 min',
    image: '👶',
    content: [
      { type: 'intro', text: 'Every parent worries when their child falls sick. While most childhood illnesses are minor and resolve on their own, certain signs indicate you should consult a pediatrician promptly. Here\'s your guide to knowing the difference.' },
      { type: 'heading', text: 'See a Pediatrician Immediately If Your Child Has:' },
      { type: 'paragraph', text: '• Fever above 102°F (39°C) lasting more than 2 days\n• Difficulty breathing or rapid breathing\n• Refusing to eat or drink for more than 12 hours\n• Severe vomiting or diarrhea (risk of dehydration)\n• Rash that doesn\'t fade when pressed\n• Unusual drowsiness or difficulty waking\n• Seizures or convulsions' },
      { type: 'heading', text: 'Common Childhood Illnesses That Need a Doctor' },
      { type: 'paragraph', text: 'Ear infections (pulling at ears, crying), urinary tract infections (pain during urination, fever), and respiratory infections (persistent cough, wheezing) all need professional treatment — home remedies aren\'t enough.' },
      { type: 'heading', text: 'Routine Pediatrician Visits' },
      { type: 'paragraph', text: 'Even when your child is healthy, regular check-ups are important:\n• Monthly for first year\n• Every 3 months (ages 1-3)\n• Every 6 months (ages 3-6)\n• Annually after age 6\n\nThese visits track growth, development milestones, and vaccinations.' },
      { type: 'heading', text: 'Vaccination Schedule' },
      { type: 'paragraph', text: 'Following India\'s National Immunization Schedule protects your child from serious diseases. Missed a vaccine? A pediatrician can create a catch-up schedule.' },
      { type: 'heading', text: 'Online Pediatric Consultation' },
      { type: 'paragraph', text: 'For non-emergency concerns — mild fever, feeding issues, minor rashes, behavioral questions — video consultation with a pediatrician is convenient and effective. You get professional advice without exposing a sick child to more germs in a waiting room.' },
    ]
  },
  {
    slug: 'mental-health-when-to-get-help',
    title: 'Mental Health: 7 Signs You Need Professional Help',
    description: 'Depression, anxiety, insomnia — when should you see a psychiatrist? Learn the signs that indicate you need professional mental health support.',
    specialization: 'Psychiatrist',
    publishedDate: '2026-08-05',
    readTime: '5 min',
    image: '🧠',
    content: [
      { type: 'intro', text: 'Mental health is as important as physical health, yet most Indians hesitate to seek help. There\'s no shame in consulting a psychiatrist — it\'s a sign of strength, not weakness. Here are 7 signs you should reach out.' },
      { type: 'heading', text: '1. Persistent Sadness or Hopelessness' },
      { type: 'paragraph', text: 'Feeling sad for more than 2 weeks, losing interest in activities you once enjoyed, or feeling empty and hopeless are classic signs of depression. It\'s a medical condition, not a character flaw — and it\'s treatable.' },
      { type: 'heading', text: '2. Overwhelming Anxiety or Worry' },
      { type: 'paragraph', text: 'If worry dominates your daily life, causes physical symptoms (racing heart, sweating, nausea), or prevents you from normal activities, professional help can make a dramatic difference.' },
      { type: 'heading', text: '3. Sleep Problems' },
      { type: 'paragraph', text: 'Chronic insomnia (can\'t fall asleep) or hypersomnia (sleeping too much) lasting more than 3 weeks often indicates an underlying mental health condition that needs treatment.' },
      { type: 'heading', text: '4. Panic Attacks' },
      { type: 'paragraph', text: 'Sudden episodes of intense fear with physical symptoms — chest pain, difficulty breathing, dizziness, trembling — are panic attacks. They\'re terrifying but highly treatable with the right approach.' },
      { type: 'heading', text: '5. Relationship or Work Problems' },
      { type: 'paragraph', text: 'When mental health issues start affecting your relationships, work performance, or daily functioning, it\'s time to seek help before things deteriorate further.' },
      { type: 'heading', text: '6. Substance Use to Cope' },
      { type: 'paragraph', text: 'Using alcohol, drugs, or medications to manage stress, anxiety, or emotional pain is a warning sign. A psychiatrist can address the root cause and provide healthier coping strategies.' },
      { type: 'heading', text: '7. Thoughts of Self-Harm' },
      { type: 'paragraph', text: 'If you\'re having thoughts of hurting yourself or ending your life, please reach out immediately. Call a helpline (Vandrevala Foundation: 1860-2662-345) or consult a psychiatrist urgently. Help is available.' },
      { type: 'heading', text: 'Online Mental Health Consultation' },
      { type: 'paragraph', text: 'Mental health consultations are particularly effective online — you can speak from the privacy of your home, without the stigma of visiting a clinic. Video calls offer the same quality of care as in-person visits for therapy and medication management.' },
    ]
  },
  {
    slug: 'back-pain-when-to-see-orthopedic',
    title: 'Back Pain: When to See an Orthopedic Doctor',
    description: 'Is your back pain serious? Learn when home remedies aren\'t enough and you need an orthopedic specialist for back, knee, or joint pain.',
    specialization: 'Orthopedic',
    publishedDate: '2026-08-06',
    readTime: '5 min',
    image: '🦴',
    content: [
      { type: 'intro', text: 'Back pain affects 80% of people at some point in their lives. While most episodes resolve within a few weeks, certain signs indicate you need professional orthopedic care. Ignoring serious back problems can lead to permanent nerve damage.' },
      { type: 'heading', text: 'See an Orthopedic Doctor Immediately If:' },
      { type: 'paragraph', text: '• Pain radiates down your leg (sciatica)\n• Numbness or tingling in legs or feet\n• Loss of bladder or bowel control\n• Pain after a fall or accident\n• Pain that worsens at night\n• Back pain with fever (possible infection)' },
      { type: 'heading', text: 'Common Causes of Back Pain' },
      { type: 'paragraph', text: 'Muscle strain is the most common cause — from lifting heavy objects, sudden movements, or poor posture. This usually heals in 2-4 weeks with rest and pain medication.' },
      { type: 'paragraph', text: 'Slip disc (herniated disc) occurs when the soft cushion between vertebrae bulges out and presses on nerves. Symptoms include shooting pain, numbness, and weakness in legs.' },
      { type: 'paragraph', text: 'Spondylosis is age-related wear of the spine. It\'s common after age 40 and causes stiffness and pain, especially in the morning.' },
      { type: 'heading', text: 'Do I Need Surgery?' },
      { type: 'paragraph', text: 'Good news: 90% of back problems are treated WITHOUT surgery. Treatment options include physiotherapy, pain medication, spinal injections, and lifestyle modifications. Surgery is only considered when conservative treatment fails after 6-12 weeks.' },
      { type: 'heading', text: 'Prevention Tips' },
      { type: 'paragraph', text: '• Maintain good posture while sitting and standing\n• Exercise regularly (even 30 minutes of walking helps)\n• Strengthen core muscles\n• Lift heavy objects with your knees, not your back\n• Take breaks if you sit for long hours\n• Maintain a healthy weight' },
      { type: 'heading', text: 'Online Orthopedic Consultation' },
      { type: 'paragraph', text: 'Many back problems can be initially assessed online. The doctor can evaluate your symptoms, recommend imaging (X-ray/MRI), prescribe medication, and suggest exercises — all through video consultation. In-person visits are needed only for physical examination or procedures.' },
    ]
  },
  {
    slug: 'dental-problems-complete-guide',
    title: 'Common Dental Problems and When to See a Dentist',
    description: 'Toothache, bleeding gums, bad breath? Learn about common dental issues and when you should visit a dentist before it gets worse.',
    specialization: 'Dentist',
    publishedDate: '2026-08-07',
    readTime: '5 min',
    image: '🦷',
    content: [
      { type: 'intro', text: 'Dental problems are among the most common health issues in India, yet many people avoid the dentist until pain becomes unbearable. Early treatment is simpler, cheaper, and less painful. Here\'s what you need to know.' },
      { type: 'heading', text: 'See a Dentist Urgently If You Have:' },
      { type: 'paragraph', text: '• Severe toothache that doesn\'t respond to painkillers\n• Swelling in the face or jaw\n• Bleeding that won\'t stop after tooth extraction\n• A knocked-out or broken tooth\n• Pus or abscess near a tooth\n• Difficulty opening your mouth' },
      { type: 'heading', text: 'Common Problems You Shouldn\'t Ignore' },
      { type: 'paragraph', text: 'Cavities start small and painless but grow until they reach the nerve, causing severe pain. A small filling costs ₹500-1000 — a root canal for an ignored cavity costs ₹5000-10000. Don\'t wait.' },
      { type: 'paragraph', text: 'Bleeding gums while brushing is NOT normal. It\'s usually gingivitis (gum inflammation) which, untreated, progresses to periodontitis — causing tooth loss. Professional cleaning reverses early gum disease.' },
      { type: 'paragraph', text: 'Persistent bad breath despite good oral hygiene can indicate gum disease, infected teeth, or other health issues. A dentist can identify the exact cause.' },
      { type: 'heading', text: 'How Often Should You Visit?' },
      { type: 'paragraph', text: 'Every 6 months for a routine check-up and cleaning — even if you have no pain. Many dental problems are painless in early stages and only a dentist can detect them.' },
      { type: 'heading', text: 'Modern Dentistry is Painless' },
      { type: 'paragraph', text: 'Worried about pain? Modern anesthesia makes most procedures painless. Laser dentistry, painless injections, and sedation options mean you can get treated comfortably.' },
      { type: 'heading', text: 'Online Dental Consultation' },
      { type: 'paragraph', text: 'While procedures require in-person visits, initial consultation — assessing your problem, prescribing pain relief, recommending treatment options — can be done online. Share photos of the affected area during a video call.' },
    ]
  },
  {
    slug: 'eye-problems-vision-care-guide',
    title: 'Eye Problems: When to See an Ophthalmologist',
    description: 'Blurry vision, eye strain, headaches? Know when common eye problems need professional attention from an ophthalmologist.',
    specialization: 'Ophthalmologist',
    publishedDate: '2026-08-08',
    readTime: '5 min',
    image: '👁️',
    content: [
      { type: 'intro', text: 'Your eyes work harder than almost any organ — processing millions of pieces of information daily. With increasing screen time, eye problems are rising rapidly in India. Here\'s when you should see an ophthalmologist.' },
      { type: 'heading', text: 'Emergency — See a Doctor Immediately:' },
      { type: 'paragraph', text: '• Sudden vision loss in one or both eyes\n• Flash of light followed by floating spots\n• Eye injury (chemical splash, foreign object)\n• Sudden severe eye pain with nausea\n• Red eye with vision changes' },
      { type: 'heading', text: 'Book an Appointment If You Notice:' },
      { type: 'paragraph', text: '• Difficulty reading or seeing distant objects\n• Frequent headaches related to vision\n• Eye strain from computers/phones\n• Dry, itchy, or watery eyes\n• Difficulty seeing at night\n• Double vision\n• Gradual change in color perception' },
      { type: 'heading', text: 'Common Eye Conditions' },
      { type: 'paragraph', text: 'Myopia (near-sightedness) is epidemic among young Indians — affecting over 30% of urban children. Early intervention with proper glasses prevents progression.' },
      { type: 'paragraph', text: 'Digital eye strain (computer vision syndrome) affects anyone spending 3+ hours on screens daily. Symptoms include headaches, dry eyes, and blurred vision. The 20-20-20 rule helps: every 20 minutes, look at something 20 feet away for 20 seconds.' },
      { type: 'paragraph', text: 'Cataracts are the leading cause of blindness in India but are 100% treatable with a simple 15-minute surgery. If your vision is getting cloudy or yellowish, get checked.' },
      { type: 'heading', text: 'Routine Eye Exams' },
      { type: 'paragraph', text: '• Children: first exam at age 3, then before starting school\n• Adults (20-39): every 5 years if no issues\n• Adults (40-54): every 2-4 years\n• Adults (55+): every 1-3 years\n• Diabetics: annually regardless of age' },
      { type: 'heading', text: 'Protecting Your Eyes Daily' },
      { type: 'paragraph', text: '• Follow the 20-20-20 rule for screen use\n• Wear UV-protective sunglasses outdoors\n• Eat green vegetables and omega-3 rich foods\n• Don\'t rub your eyes with dirty hands\n• Use proper lighting while reading\n• Get adequate sleep (7-8 hours)' },
    ]
  },
  {
    slug: 'stomach-problems-gastroenterologist',
    title: 'Stomach Problems: When to Consult a Gastroenterologist',
    description: 'Acidity, bloating, constipation? Learn when digestive problems need a gastroenterologist and what conditions they treat.',
    specialization: 'Gastroenterologist',
    publishedDate: '2026-08-09',
    readTime: '5 min',
    image: '🤢',
    content: [
      { type: 'intro', text: 'Digestive problems are incredibly common in India — from acidity and bloating to more serious conditions like IBS and liver disease. While occasional stomach issues are normal, persistent symptoms need professional evaluation.' },
      { type: 'heading', text: 'See a Gastroenterologist If You Experience:' },
      { type: 'paragraph', text: '• Acidity/heartburn more than twice a week\n• Blood in stool or black-colored stools\n• Unexplained weight loss\n• Persistent abdominal pain\n• Difficulty swallowing\n• Chronic diarrhea or constipation (>3 weeks)\n• Jaundice (yellowing of skin/eyes)\n• Bloating that doesn\'t improve with diet changes' },
      { type: 'heading', text: 'Common Conditions' },
      { type: 'paragraph', text: 'GERD (acid reflux) affects millions. While antacids provide temporary relief, chronic GERD can damage the food pipe. A gastroenterologist provides long-term solutions beyond over-the-counter medication.' },
      { type: 'paragraph', text: 'IBS (Irritable Bowel Syndrome) causes alternating constipation and diarrhea, bloating, and cramps. It\'s manageable with the right diet, medication, and stress management — but needs proper diagnosis first.' },
      { type: 'paragraph', text: 'Fatty liver disease is silently affecting 30-40% of urban Indians. Often discovered accidentally during tests, untreated fatty liver can progress to liver failure. Lifestyle changes can reverse it if caught early.' },
      { type: 'heading', text: 'When Stomach Problems Are Serious' },
      { type: 'paragraph', text: 'Most stomach issues are benign, but these signs need urgent attention:\n• Blood in vomit or stool\n• Sudden severe abdominal pain\n• High fever with abdominal pain\n• Inability to keep any food/water down for 24 hours\n• Significant unexplained weight loss' },
      { type: 'heading', text: 'Lifestyle Changes That Help' },
      { type: 'paragraph', text: '• Eat smaller, more frequent meals\n• Avoid spicy, oily food late at night\n• Don\'t lie down within 2 hours of eating\n• Reduce stress (yoga, meditation help)\n• Stay hydrated\n• Include fiber in your diet\n• Limit alcohol and caffeine' },
      { type: 'heading', text: 'Online Consultation for Digestive Issues' },
      { type: 'paragraph', text: 'Gastroenterology consultations work well online — the doctor can assess symptoms, review test reports, prescribe medication, and recommend dietary changes through video call. Procedures like endoscopy require in-person visits.' },
    ]
  },
  {
    slug: 'diabetes-thyroid-endocrinologist',
    title: 'Diabetes and Thyroid: When to See an Endocrinologist',
    description: 'Managing diabetes, thyroid disorders, or hormonal imbalances? Learn when you need an endocrinologist and what they treat.',
    specialization: 'Endocrinologist',
    publishedDate: '2026-08-10',
    readTime: '5 min',
    image: '💉',
    content: [
      { type: 'intro', text: 'India is the diabetes capital of the world with over 77 million diabetics. Thyroid disorders affect 1 in 10 Indians. These hormonal conditions need specialist care — not just a general physician. Here\'s when to see an endocrinologist.' },
      { type: 'heading', text: 'See an Endocrinologist If:' },
      { type: 'paragraph', text: '• Your diabetes isn\'t controlled despite medication\n• You need insulin management\n• You have diabetes complications (kidney, eye, nerve problems)\n• Thyroid medication isn\'t working well\n• You have PCOD with hormonal imbalance\n• Unexplained weight gain or loss\n• Fatigue, mood swings, or irregular periods\n• Calcium or vitamin D deficiency not responding to supplements' },
      { type: 'heading', text: 'Diabetes — More Than Just Sugar Control' },
      { type: 'paragraph', text: 'Type 2 diabetes is progressive — what works today may not work in 5 years. An endocrinologist adjusts your treatment plan over time, monitors complications, and helps prevent heart disease, kidney failure, and nerve damage.' },
      { type: 'paragraph', text: 'If your HbA1c is above 7% despite medication, or you\'re experiencing numbness in feet, vision changes, or frequent infections — you need specialist care urgently.' },
      { type: 'heading', text: 'Thyroid Disorders' },
      { type: 'paragraph', text: 'Hypothyroidism (low thyroid) causes fatigue, weight gain, cold intolerance, and depression. Hyperthyroidism (overactive thyroid) causes weight loss, anxiety, tremors, and rapid heartbeat. Both need proper dosage management by a specialist.' },
      { type: 'paragraph', text: 'Thyroid nodules and goiter need evaluation to rule out cancer. Most are benign but should be monitored regularly.' },
      { type: 'heading', text: 'PCOD and Hormonal Issues' },
      { type: 'paragraph', text: 'PCOD involves insulin resistance, high androgens, and metabolic issues that go beyond just irregular periods. An endocrinologist addresses the metabolic root cause — not just the symptoms.' },
      { type: 'heading', text: 'Online Endocrinology Consultation' },
      { type: 'paragraph', text: 'Endocrinology is ideal for online consultations — most follow-ups involve reviewing blood reports, adjusting medication doses, and discussing lifestyle changes. Share your lab reports during a video call and get expert advice from anywhere in India.' },
    ]
  },
  {
    slug: 'ear-nose-throat-ent-problems',
    title: 'Ear, Nose & Throat Problems: When to See an ENT Specialist',
    description: 'Ear pain, sinus issues, tonsillitis, snoring? Learn when ENT problems need specialist attention and what treatments are available.',
    specialization: 'ENT Specialist',
    publishedDate: '2026-08-11',
    readTime: '5 min',
    image: '👂',
    content: [
      { type: 'intro', text: 'ENT problems — ear infections, sinusitis, tonsillitis, hearing loss — are among the most common reasons for doctor visits in India. While many resolve with basic treatment, persistent or severe symptoms need specialist care.' },
      { type: 'heading', text: 'See an ENT Specialist If You Have:' },
      { type: 'paragraph', text: '• Ear pain lasting more than 2-3 days\n• Sudden hearing loss or ringing (tinnitus)\n• Chronic sinus congestion (>4 weeks)\n• Frequent sore throats (>5 per year)\n• Snoring with breathing pauses during sleep\n• Nosebleeds that don\'t stop\n• Lump in the neck\n• Voice changes lasting more than 2 weeks' },
      { type: 'heading', text: 'Common ENT Conditions' },
      { type: 'paragraph', text: 'Sinusitis causes facial pain, nasal congestion, and headaches. Acute sinusitis resolves in 2-4 weeks, but chronic sinusitis (>12 weeks) needs specialist evaluation and possibly surgery.' },
      { type: 'paragraph', text: 'Tonsillitis — recurring tonsil infections (>5 times per year) may need surgical removal (tonsillectomy). Modern techniques make this a simple day-care procedure.' },
      { type: 'paragraph', text: 'Sleep apnea — loud snoring with breathing pauses is not just annoying, it increases heart attack and stroke risk. An ENT specialist can identify the obstruction and offer treatment.' },
      { type: 'heading', text: 'Hearing Loss in India' },
      { type: 'paragraph', text: 'Over 60 million Indians have significant hearing loss. Causes include ear infections, noise exposure, aging, and earwax buildup. Early intervention with hearing aids or treatment prevents social isolation and cognitive decline.' },
      { type: 'heading', text: 'When Children Need an ENT' },
      { type: 'paragraph', text: '• Frequent ear infections (>3 per year)\n• Mouth breathing or snoring\n• Speech delay (possible hearing issue)\n• Enlarged adenoids causing breathing difficulty\n• Recurrent tonsillitis affecting school attendance' },
      { type: 'heading', text: 'Online ENT Consultation' },
      { type: 'paragraph', text: 'Initial ENT assessment, medication for infections, allergy management, and follow-ups work well online. Share photos or videos of symptoms during your video call. Procedures require in-person visits.' },
    ]
  },
  {
    slug: 'neurological-symptoms-brain-health',
    title: 'Brain & Nerve Problems: When to See a Neurologist',
    description: 'Headaches, dizziness, numbness, memory problems? Learn which neurological symptoms need specialist attention and when to worry.',
    specialization: 'Neurologist',
    publishedDate: '2026-08-12',
    readTime: '5 min',
    image: '🤕',
    content: [
      { type: 'intro', text: 'Neurological symptoms can be frightening — headaches that won\'t go away, sudden numbness, memory lapses. While most are benign, some indicate serious conditions that need urgent attention. Here\'s your guide to knowing when to see a neurologist.' },
      { type: 'heading', text: 'Emergency — Go to Hospital Now:' },
      { type: 'paragraph', text: '• Sudden severe headache ("worst headache of my life")\n• Sudden weakness or numbness on one side of body\n• Sudden difficulty speaking or understanding speech\n• Sudden vision loss\n• Seizure for the first time\n• Loss of consciousness\n\nThese could indicate stroke or brain hemorrhage. Every minute counts.' },
      { type: 'heading', text: 'Book a Neurologist If You Experience:' },
      { type: 'paragraph', text: '• Frequent headaches/migraines (>4 per month)\n• Persistent numbness or tingling in hands/feet\n• Dizziness or vertigo episodes\n• Memory problems affecting daily life\n• Tremors in hands\n• Chronic neck or back pain with nerve symptoms\n• Sleep disorders (insomnia, sleep walking)\n• Facial pain or weakness' },
      { type: 'heading', text: 'Migraine — More Than Just a Headache' },
      { type: 'paragraph', text: 'Migraines affect 15% of Indians and cause throbbing pain, nausea, light sensitivity, and can be disabling. A neurologist provides preventive treatment that reduces frequency and severity — not just painkillers for each attack.' },
      { type: 'heading', text: 'Epilepsy (Seizures)' },
      { type: 'paragraph', text: 'Epilepsy is one of the most common neurological conditions. With proper medication, 70% of people with epilepsy can become seizure-free. Never stop anti-seizure medication without consulting your neurologist.' },
      { type: 'heading', text: 'Nerve Pain (Neuropathy)' },
      { type: 'paragraph', text: 'Burning, tingling, or numbness in feet and hands — especially common in diabetics — indicates nerve damage. Early treatment prevents progression. Don\'t dismiss it as "just circulation problems."' },
      { type: 'heading', text: 'Online Neurology Consultation' },
      { type: 'paragraph', text: 'Neurology consultations are effective online for headache management, medication review, follow-ups, and initial symptom evaluation. The neurologist may recommend MRI or nerve conduction tests based on your consultation.' },
    ]
  },
  {
    slug: 'kidney-health-urologist-guide',
    title: 'Kidney & Urinary Problems: When to See a Urologist',
    description: 'UTIs, kidney stones, frequent urination? Learn when urinary problems need a urologist and how to protect your kidney health.',
    specialization: 'Urologist',
    publishedDate: '2026-08-13',
    readTime: '5 min',
    image: '💧',
    content: [
      { type: 'intro', text: 'Kidney and urinary problems are common but often ignored due to embarrassment. From kidney stones to UTIs to prostate issues, early treatment prevents serious complications. Here\'s when you need a urologist.' },
      { type: 'heading', text: 'See a Urologist Urgently If:' },
      { type: 'paragraph', text: '• Blood in urine (even once)\n• Severe flank pain (possible kidney stone)\n• Inability to urinate\n• Fever with urinary symptoms\n• Testicular pain or swelling\n• Painful urination with discharge' },
      { type: 'heading', text: 'Common Urological Problems' },
      { type: 'paragraph', text: 'Kidney stones affect 12% of Indians. Severe flank pain radiating to the groin is the classic symptom. Small stones pass naturally with hydration; larger ones may need lithotripsy (shock wave treatment) or surgery.' },
      { type: 'paragraph', text: 'UTI (Urinary Tract Infection) is extremely common in women — 50% will have at least one in their lifetime. Symptoms include burning urination, frequent urge, and cloudy urine. Needs antibiotics — don\'t self-medicate.' },
      { type: 'paragraph', text: 'Prostate problems affect most men over 50. Symptoms include weak stream, frequent urination at night, and difficulty starting urination. Most cases are benign enlargement (BPH), not cancer.' },
      { type: 'heading', text: 'Protecting Your Kidneys' },
      { type: 'paragraph', text: '• Drink 2-3 liters of water daily\n• Don\'t hold urine for long periods\n• Reduce salt intake\n• Control diabetes and blood pressure\n• Avoid excessive painkillers (NSAIDs)\n• Get annual kidney function tests after age 40' },
      { type: 'heading', text: 'When to Get Kidney Function Tests' },
      { type: 'paragraph', text: 'If you have diabetes, high BP, family history of kidney disease, or take regular medications — annual creatinine and urine tests can catch kidney problems early when they\'re reversible.' },
      { type: 'heading', text: 'Online Urology Consultation' },
      { type: 'paragraph', text: 'Many urological concerns — UTI treatment, kidney stone management advice, prostate symptom assessment, and follow-ups — can be handled through video consultation. Procedures require in-person visits.' },
    ]
  },
  {
    slug: 'breathing-problems-pulmonologist',
    title: 'Breathing Problems: When to See a Pulmonologist',
    description: 'Asthma, chronic cough, breathlessness? Know when lung problems need a specialist and what a pulmonologist can do for you.',
    specialization: 'Pulmonologist',
    publishedDate: '2026-08-14',
    readTime: '5 min',
    image: '🫁',
    content: [
      { type: 'intro', text: 'With rising air pollution in Indian cities, respiratory problems are increasing rapidly. Asthma, COPD, and chronic cough affect millions. Here\'s when breathing problems need specialist attention from a pulmonologist.' },
      { type: 'heading', text: 'See a Pulmonologist If:' },
      { type: 'paragraph', text: '• Cough lasting more than 3 weeks\n• Breathlessness during routine activities\n• Wheezing or chest tightness\n• Coughing up blood\n• Frequent respiratory infections (>3 per year)\n• Asthma not controlled with inhalers\n• Snoring with daytime sleepiness\n• Exposure to TB or abnormal chest X-ray' },
      { type: 'heading', text: 'Asthma — India\'s Growing Problem' },
      { type: 'paragraph', text: 'Over 30 million Indians have asthma. Many are undertreated — using only emergency inhalers instead of preventive therapy. A pulmonologist creates a long-term plan that controls symptoms and prevents attacks.' },
      { type: 'paragraph', text: 'Myth: "Inhalers are addictive." Reality: Inhalers are the safest and most effective asthma treatment. They deliver medicine directly to the lungs with minimal side effects.' },
      { type: 'heading', text: 'COPD — The Silent Killer' },
      { type: 'paragraph', text: 'Chronic Obstructive Pulmonary Disease affects smokers and those exposed to indoor air pollution (cooking fuel). Progressive breathlessness, chronic cough, and frequent infections are warning signs. Early treatment slows progression.' },
      { type: 'heading', text: 'Tuberculosis (TB)' },
      { type: 'paragraph', text: 'India has the highest TB burden globally. Symptoms: persistent cough >2 weeks, evening fever, night sweats, weight loss. TB is completely curable with 6 months of proper medication — but incomplete treatment creates drug-resistant TB.' },
      { type: 'heading', text: 'Protecting Your Lungs' },
      { type: 'paragraph', text: '• Stop smoking (even passive smoking)\n• Use N95 mask in polluted areas\n• Exercise regularly to improve lung capacity\n• Get annual flu vaccination\n• Ensure good ventilation in kitchen\n• Avoid burning mosquito coils indoors' },
      { type: 'heading', text: 'Online Pulmonology Consultation' },
      { type: 'paragraph', text: 'Asthma management, COPD follow-ups, cough evaluation, and medication adjustment work well online. The doctor may recommend spirometry (lung function test) or chest X-ray based on your consultation.' },
    ]
  },
  {
    slug: 'physiotherapy-pain-management',
    title: 'Physiotherapy: When Exercises Are Better Than Medicine',
    description: 'Chronic pain, post-surgery recovery, sports injuries? Learn when physiotherapy is the answer and how it helps heal without medication.',
    specialization: 'Physiotherapist',
    publishedDate: '2026-08-15',
    readTime: '5 min',
    image: '🏃',
    content: [
      { type: 'intro', text: 'Physiotherapy is one of the most underused treatments in India. Many people rely on painkillers for months when targeted exercises could solve the problem permanently. Here\'s when physiotherapy should be your first choice.' },
      { type: 'heading', text: 'Physiotherapy Is Best For:' },
      { type: 'paragraph', text: '• Chronic back or neck pain\n• Post-surgery rehabilitation (knee replacement, spine surgery)\n• Sports injuries (sprains, tears, fractures)\n• Frozen shoulder\n• Knee pain and arthritis\n• Stroke recovery\n• Balance and mobility problems in elderly\n• Pregnancy and postpartum body recovery' },
      { type: 'heading', text: 'Why Physiotherapy Over Painkillers?' },
      { type: 'paragraph', text: 'Painkillers mask the symptom. Physiotherapy fixes the cause. A torn muscle, weak joint, or stiff spine won\'t heal with tablets — it needs targeted movement, strengthening, and stretching. The results are permanent.' },
      { type: 'paragraph', text: 'Long-term painkiller use causes stomach ulcers, kidney damage, and dependency. Physiotherapy has zero side effects and builds your body\'s natural strength.' },
      { type: 'heading', text: 'Common Conditions Treated' },
      { type: 'paragraph', text: 'Frozen shoulder — one of the most common problems in 40-60 age group. Without physiotherapy, it can take 2-3 years to resolve naturally. With proper exercises, recovery happens in 3-6 months.' },
      { type: 'paragraph', text: 'Knee osteoarthritis — exercises to strengthen quadriceps and improve joint mobility can delay or avoid knee replacement surgery. Studies show physiotherapy is as effective as surgery for moderate arthritis.' },
      { type: 'heading', text: 'What to Expect in Physiotherapy' },
      { type: 'paragraph', text: '• Initial assessment of your problem\n• Customized exercise plan\n• Hands-on techniques (mobilization, stretching)\n• Modalities like ultrasound, TENS for pain relief\n• Home exercise program to continue independently\n• Progress tracking over 4-8 weeks' },
      { type: 'heading', text: 'Online Physiotherapy Consultation' },
      { type: 'paragraph', text: 'Initial assessment, exercise demonstration, and progress reviews work effectively through video call. The physiotherapist watches your movements, corrects form, and progresses your program — all remotely. Great for ongoing rehabilitation.' },
    ]
  },
  {
    slug: 'is-online-doctor-consultation-safe',
    title: 'Is Online Doctor Consultation Safe and Legal in India?',
    description: 'Wondering if consulting a doctor online is safe, legal, and effective? Here\'s everything you need to know about teleconsultation in India.',
    specialization: 'General Physician',
    publishedDate: '2026-08-12',
    readTime: '5 min',
    image: '💻',
    content: [
      { type: 'intro', text: 'Online doctor consultation has grown rapidly in India, but many people still wonder — is it safe? Is it legal? Will I get the same quality of care as an in-person visit? This guide answers the most common questions honestly.' },
      { type: 'heading', text: 'Is Online Consultation Legal in India?' },
      { type: 'paragraph', text: 'Yes. In 2020, the Government of India and the Medical Council issued the Telemedicine Practice Guidelines, formally allowing registered doctors to consult patients remotely. Any doctor with a valid medical registration can legally provide teleconsultation.' },
      { type: 'heading', text: 'Is It Safe?' },
      { type: 'paragraph', text: 'For most non-emergency concerns, yes. You consult the same qualified, registered doctors you would meet in a clinic. On a trusted platform, every doctor\'s qualifications and registration are verified before they can see patients. Always check that the doctor is registered — on ProMedicoz, this is shown on every doctor\'s profile.' },
      { type: 'heading', text: 'What Can Be Treated Online?' },
      { type: 'paragraph', text: '• Fever, cold, cough, and common infections\n• Skin problems (with photos)\n• Follow-ups and report reviews\n• Managing diabetes, thyroid, blood pressure\n• Mental health consultations\n• Prescription refills and second opinions\n• General health advice and preventive care' },
      { type: 'heading', text: 'What Needs an In-Person Visit?' },
      { type: 'paragraph', text: 'Emergencies, conditions needing physical examination, procedures, and anything the doctor decides requires hands-on assessment. A good online doctor will always tell you honestly when you need to visit in person — this is a feature, not a limitation.' },
      { type: 'heading', text: 'Will I Get a Valid Prescription?' },
      { type: 'paragraph', text: 'Yes. A registered doctor can issue a valid digital prescription during teleconsultation, which pharmacies accept. On ProMedicoz, your prescription appears in your account right after the consultation.' },
      { type: 'heading', text: 'How Much Does It Cost?' },
      { type: 'paragraph', text: 'On ProMedicoz, browsing and booking is free — you only pay the doctor\'s consultation fee, set by each doctor and paid directly to them. There are no hidden platform charges.' },
      { type: 'heading', text: 'The Bottom Line' },
      { type: 'paragraph', text: 'Online consultation is a safe, legal, and convenient option for most everyday health needs — saving you travel, waiting rooms, and time. For emergencies, always go to a hospital. For everything else, a verified doctor is now just a couple of minutes away.' },
    ]
  },
  {
    slug: 'frequent-headaches-causes-when-to-worry',
    title: 'Frequent Headaches: Causes and When to Worry',
    description: 'Getting headaches often? Learn the common causes, simple remedies, and the warning signs that mean you should see a doctor.',
    specialization: 'Neurologist',
    publishedDate: '2026-08-13',
    readTime: '5 min',
    image: '🤕',
    content: [
      { type: 'intro', text: 'Almost everyone gets headaches, but frequent or severe ones can disrupt your life — and occasionally signal something serious. Here\'s how to understand your headaches and know when it\'s time to see a doctor.' },
      { type: 'heading', text: 'Common Causes of Frequent Headaches' },
      { type: 'paragraph', text: '• Stress and tension (the most common cause)\n• Dehydration and skipping meals\n• Poor sleep or too much screen time\n• Eye strain or an outdated spectacle prescription\n• Caffeine (too much, or withdrawal)\n• Sinus problems\n• Migraine' },
      { type: 'heading', text: 'Tension Headache vs Migraine' },
      { type: 'paragraph', text: 'A tension headache feels like a tight band around your head — dull and on both sides. A migraine is usually one-sided, throbbing, and often comes with nausea, and sensitivity to light or sound. Migraines need proper treatment, not just painkillers.' },
      { type: 'heading', text: 'Simple Remedies to Try First' },
      { type: 'paragraph', text: '• Drink water — dehydration is an underrated cause\n• Take regular screen breaks (20-20-20 rule)\n• Keep regular sleep and meal times\n• Manage stress with short walks or breathing\n• Limit painkillers to a few days a week — overusing them causes "rebound" headaches' },
      { type: 'heading', text: 'Warning Signs — See a Doctor' },
      { type: 'paragraph', text: '• A sudden, severe "worst headache of my life"\n• Headache with fever, stiff neck, or confusion\n• Headache after a head injury\n• Headaches that keep getting worse over days/weeks\n• Headache with vision loss, weakness, or difficulty speaking\n• New headaches after age 50\n\nThe first three can be emergencies — seek care immediately.' },
      { type: 'heading', text: 'Can a Doctor Help Online?' },
      { type: 'paragraph', text: 'Yes. For recurring or chronic headaches (not the emergency signs above), a doctor can review your pattern, identify triggers, treat migraine properly, and advise when a scan is needed — all through a video consultation.' },
    ]
  },
  {
    slug: 'fever-home-care-vs-see-doctor',
    title: 'Fever: When Home Care Is Enough and When to See a Doctor',
    description: 'Running a fever? Learn safe home care, which medicines help, and the exact signs that mean you should consult a doctor without delay.',
    specialization: 'General Physician',
    publishedDate: '2026-08-14',
    readTime: '5 min',
    image: '🌡️',
    content: [
      { type: 'intro', text: 'Fever is one of the most common reasons people worry — but it\'s usually the body\'s natural way of fighting infection, not a disease itself. Here\'s how to care for a fever at home and, importantly, when it needs a doctor.' },
      { type: 'heading', text: 'What Counts as a Fever?' },
      { type: 'paragraph', text: 'A body temperature of 100.4°F (38°C) or above is a fever. Most fevers from common viral infections are mild and settle in 2-3 days.' },
      { type: 'heading', text: 'Safe Home Care' },
      { type: 'paragraph', text: '• Rest and drink plenty of fluids (water, ORS, soups)\n• Paracetamol as directed on the pack for comfort\n• Dress lightly; don\'t bundle up in blankets\n• A lukewarm sponge if very uncomfortable — not cold water\n• Monitor the temperature and how you feel overall' },
      { type: 'heading', text: 'See a Doctor If:' },
      { type: 'paragraph', text: '• Fever stays above 102°F (39°C) or lasts more than 3 days\n• Severe headache, stiff neck, or a rash that doesn\'t fade\n• Breathing difficulty or chest pain\n• Persistent vomiting or signs of dehydration\n• Confusion or unusual drowsiness\n• Fever after travel to a malaria/dengue area' },
      { type: 'heading', text: 'Fever in Children and the Elderly' },
      { type: 'paragraph', text: 'Be more cautious with infants, young children, elderly people, and anyone with diabetes, heart, or lung conditions. In a baby under 3 months, any fever needs a doctor the same day.' },
      { type: 'heading', text: 'Why Not Just Take an Antibiotic?' },
      { type: 'paragraph', text: 'Most fevers are viral, and antibiotics do nothing for viruses — taking them unnecessarily is harmful and fuels antibiotic resistance. A doctor decides whether an antibiotic is actually needed.' },
      { type: 'heading', text: 'Consult Online for Fever' },
      { type: 'paragraph', text: 'For an uncomplicated fever without the warning signs above, an online consultation is a convenient way to get advice, the right medication, and a clear plan on what to watch for — without stepping out while unwell.' },
    ]
  },
  {
    slug: 'how-to-book-doctor-online-india',
    title: 'How to Consult a Doctor from Home in India (Step by Step)',
    description: 'New to online doctor consultation? A simple step-by-step guide to finding a verified doctor and booking an appointment from your phone.',
    specialization: 'General Physician',
    publishedDate: '2026-08-15',
    readTime: '4 min',
    image: '📲',
    content: [
      { type: 'intro', text: 'Consulting a doctor no longer means travelling and waiting for hours. If you have a phone and internet, you can consult a verified doctor from home in a few minutes. Here\'s exactly how.' },
      { type: 'heading', text: 'Step 1: Find the Right Doctor' },
      { type: 'paragraph', text: 'Search by your symptom or the specialization you need. You can also filter by city, consultation fee, and even the language the doctor speaks — so you can talk comfortably. Each profile shows the doctor\'s qualifications, experience, fee, and patient reviews.' },
      { type: 'heading', text: 'Step 2: Pick a Time Slot' },
      { type: 'paragraph', text: 'Choose a date and an available time, and select how you\'d like to consult — video call, phone call, or in-person at the clinic.' },
      { type: 'heading', text: 'Step 3: Confirmation' },
      { type: 'paragraph', text: 'The doctor confirms your appointment, usually within a few hours. You\'ll be notified in the app (and on your phone if you enable notifications).' },
      { type: 'heading', text: 'Step 4: Pay the Doctor Directly' },
      { type: 'paragraph', text: 'After confirmation, you pay the consultation fee directly to the doctor via UPI. The platform doesn\'t hold your money or add charges.' },
      { type: 'heading', text: 'Step 5: Consult' },
      { type: 'paragraph', text: 'At your appointment time, join the secure video or phone call right inside the app — no separate software needed. For in-person, simply visit the clinic. Afterwards, your prescription appears in your account automatically.' },
      { type: 'heading', text: 'Tips for a Good Online Consultation' },
      { type: 'paragraph', text: '• Sit in a quiet, well-lit place\n• Keep your medicines and past reports handy\n• Note down your symptoms and questions beforehand\n• For skin issues, have clear photos ready\n• Be honest and complete about your history' },
      { type: 'heading', text: 'Register with Just a Phone Number' },
      { type: 'paragraph', text: 'On ProMedicoz you can sign up with only your phone number — email is optional — and you can even book on behalf of family members. Getting quality healthcare has never been simpler.' },
    ]
  },
  {
    slug: 'silent-signs-high-blood-sugar',
    title: '7 Silent Signs Your Blood Sugar May Be High',
    description: 'Diabetes often shows no obvious symptoms for years. Here are 7 quiet warning signs of high blood sugar you should never ignore — and when to get tested.',
    specialization: 'Endocrinologist',
    publishedDate: '2026-08-16',
    readTime: '5 min',
    image: '🩸',
    content: [
      { type: 'intro', text: 'India is often called the "diabetes capital of the world" — and the scariest part is that high blood sugar can quietly damage your body for years before you feel truly unwell. Many people only find out after complications begin. Here are 7 silent signs worth paying attention to.' },
      { type: 'heading', text: '1. You\'re Always Thirsty (and Peeing More)' },
      { type: 'paragraph', text: 'When blood sugar is high, your kidneys work overtime to flush out the excess — pulling water with it. The result: constant thirst and frequent urination, especially at night. It\'s one of the earliest and most common signs.' },
      { type: 'heading', text: '2. Unusual Tiredness' },
      { type: 'paragraph', text: 'When sugar can\'t get into your cells properly, your body is starved of energy even though there\'s plenty of fuel in the blood. Feeling drained after meals or through the day — with no other reason — deserves a check.' },
      { type: 'heading', text: '3. Slow-Healing Cuts and Frequent Infections' },
      { type: 'paragraph', text: 'High sugar impairs circulation and your immune response. Wounds that take weeks to heal, or repeated skin, gum, or urinary infections, can be a red flag.' },
      { type: 'heading', text: '4. Tingling or Numbness in Hands and Feet' },
      { type: 'paragraph', text: 'Excess sugar slowly damages nerves (neuropathy). Early on it feels like tingling, "pins and needles," or numbness in the feet — easy to dismiss, but important to catch early.' },
      { type: 'heading', text: '5. Blurred Vision' },
      { type: 'paragraph', text: 'High sugar can pull fluid into the lens of your eye, blurring vision. It often fluctuates. Long-term, uncontrolled diabetes is a leading cause of blindness — but it\'s preventable with control.' },
      { type: 'heading', text: '6. Unexplained Weight Loss' },
      { type: 'paragraph', text: 'Losing weight without trying sounds nice, but when the body can\'t use sugar for energy, it burns muscle and fat instead. Sudden unexplained weight loss should always be checked.' },
      { type: 'heading', text: '7. Darkened Skin Patches' },
      { type: 'paragraph', text: 'Velvety dark patches on the neck, armpits, or knuckles (acanthosis nigricans) are a visible sign of insulin resistance — often the stage before full diabetes.' },
      { type: 'heading', text: 'The Good News' },
      { type: 'paragraph', text: 'A simple blood test (fasting sugar and HbA1c) can catch this early. If caught at the "pre-diabetes" stage, it can often be reversed with diet, exercise, and lifestyle changes — no medication needed. The earlier you know, the more you can do.' },
      { type: 'heading', text: 'When to Get Checked' },
      { type: 'paragraph', text: 'Get a sugar test if you have any of these signs, are over 35, are overweight, or have a family history of diabetes. An online consultation is a simple first step — a doctor can review your symptoms and reports and tell you exactly which tests to do.' },
    ]
  },
  {
    slug: 'always-tired-reasons-fatigue',
    title: 'Always Tired? 8 Reasons You Feel Exhausted (That Aren\'t Just "Lack of Sleep")',
    description: 'Feeling tired all the time even after resting? From thyroid and anaemia to vitamin deficiency and stress — here are 8 real medical causes of constant fatigue.',
    specialization: 'General Physician',
    publishedDate: '2026-08-17',
    readTime: '6 min',
    image: '😴',
    content: [
      { type: 'intro', text: '"I\'m tired all the time" is one of the most common things people tell their doctor — and one of the most ignored. If you\'re exhausted despite sleeping enough, your body may be signalling something treatable. Here are 8 common reasons, most of which are easy to test for.' },
      { type: 'heading', text: '1. Low Iron (Anaemia)' },
      { type: 'paragraph', text: 'Extremely common in India, especially in women. Low iron means less oxygen reaching your muscles and brain — leaving you tired, breathless, and pale. A simple blood test confirms it, and it\'s very treatable.' },
      { type: 'heading', text: '2. Thyroid Problems' },
      { type: 'paragraph', text: 'An underactive thyroid (hypothyroidism) slows your whole body down — fatigue, weight gain, feeling cold, low mood. It affects 1 in 10 Indians and is easily managed once diagnosed.' },
      { type: 'heading', text: '3. Vitamin D or B12 Deficiency' },
      { type: 'paragraph', text: 'Despite all our sunshine, vitamin D deficiency is widespread (we stay indoors). B12 deficiency is common too, especially in vegetarians. Both cause deep tiredness, body aches, and low mood — and both are fixed with supplements.' },
      { type: 'heading', text: '4. Uncontrolled Blood Sugar' },
      { type: 'paragraph', text: 'Both high and low blood sugar cause fatigue. Persistent tiredness with thirst or frequent urination is worth a sugar test.' },
      { type: 'heading', text: '5. Poor Sleep Quality (Not Just Quantity)' },
      { type: 'paragraph', text: 'You can sleep 8 hours and still be exhausted if the sleep is broken — often from snoring/sleep apnoea, late-night screens, or stress. Quality matters as much as hours.' },
      { type: 'heading', text: '6. Stress, Anxiety, or Depression' },
      { type: 'paragraph', text: 'Mental health drains physical energy. Constant fatigue with low motivation, poor sleep, or feeling low can be a sign that your mind needs support — and that\'s treatable too.' },
      { type: 'heading', text: '7. Dehydration and Poor Diet' },
      { type: 'paragraph', text: 'Skipping meals, too much tea/coffee, and not enough water leave your body running on empty. Sometimes the fix is as simple as regular meals and hydration.' },
      { type: 'heading', text: '8. Doing Too Much, Resting Too Little' },
      { type: 'paragraph', text: 'Sometimes fatigue is genuinely your body asking for rest. But if you\'ve rested and it hasn\'t helped, don\'t just push through — get it checked.' },
      { type: 'heading', text: 'When to See a Doctor' },
      { type: 'paragraph', text: 'If tiredness lasts more than 2-3 weeks despite rest, or comes with weight loss, breathlessness, or low mood, see a doctor. A few basic blood tests (iron, thyroid, sugar, vitamin D/B12) usually reveal the cause. You can start with an online consultation — the doctor will tell you which tests to do and review the results with you.' },
    ]
  },
  {
    slug: 'high-bp-the-silent-killer',
    title: 'High Blood Pressure: Why It\'s Called the "Silent Killer"',
    description: 'High BP usually has NO symptoms — until it causes a heart attack, stroke, or kidney damage. Here\'s what every adult should know, and how to check yours.',
    specialization: 'Cardiologist',
    publishedDate: '2026-08-18',
    readTime: '5 min',
    image: '🩺',
    content: [
      { type: 'intro', text: 'High blood pressure (hypertension) affects a huge share of Indian adults — and most don\'t know they have it. It\'s called the "silent killer" because it quietly damages your heart, brain, and kidneys for years without a single symptom. Here\'s what you need to know.' },
      { type: 'heading', text: 'Why "Silent"?' },
      { type: 'paragraph', text: 'Most people with high BP feel completely normal. There\'s usually no headache, no dizziness — nothing. That\'s exactly why it\'s dangerous: by the time symptoms appear, damage may already be done. The only way to know is to measure it.' },
      { type: 'heading', text: 'What the Numbers Mean' },
      { type: 'paragraph', text: '• Normal: below 120/80\n• Elevated: 120-129 / below 80\n• High (Stage 1): 130-139 / 80-89\n• High (Stage 2): 140/90 or above\n\nA single high reading isn\'t a diagnosis — it should be confirmed on more than one occasion.' },
      { type: 'heading', text: 'What Untreated High BP Can Cause' },
      { type: 'paragraph', text: '• Heart attack and heart failure\n• Stroke\n• Kidney damage\n• Vision loss\n\nThe scary part: all of this can happen without any warning symptoms first.' },
      { type: 'heading', text: 'Who Should Get Checked' },
      { type: 'paragraph', text: 'Every adult should know their numbers. Check more often if you\'re over 30, overweight, have diabetes, a family history, a salty diet, high stress, or a desk-bound lifestyle. It takes 2 minutes at any clinic or pharmacy.' },
      { type: 'heading', text: 'The Good News: It\'s Very Controllable' },
      { type: 'paragraph', text: 'High BP can\'t always be "cured," but it\'s easily controlled — reducing salt, regular walking, losing a little weight, cutting alcohol/smoking, managing stress, and medication where needed. Controlled BP dramatically lowers your risk of heart attack and stroke.' },
      { type: 'heading', text: 'Talk to a Doctor' },
      { type: 'paragraph', text: 'If your readings are high, or you have risk factors, consult a doctor. Blood pressure is one of the easiest conditions to manage online — the doctor reviews your readings, advises lifestyle changes, and adjusts medication over video calls. Don\'t wait for a symptom that may never come until it\'s too late.' },
    ]
  },
  {
    slug: 'stop-googling-symptoms-do-this-instead',
    title: 'Stop Googling Your Symptoms at 2 AM — Do This Instead',
    description: 'Searching your symptoms online often leads to panic and wrong conclusions. Here\'s why "Dr. Google" misleads you — and a calmer, smarter way to get real answers.',
    specialization: 'General Physician',
    publishedDate: '2026-08-19',
    readTime: '4 min',
    image: '🔍',
    content: [
      { type: 'intro', text: 'We\'ve all done it — a strange ache at midnight, and within minutes Google has convinced us it\'s something terrifying. Studies show most people search their symptoms online, and many do it even after seeing a doctor. Here\'s why that habit often does more harm than good — and what actually helps.' },
      { type: 'heading', text: 'Why "Dr. Google" Misleads You' },
      { type: 'paragraph', text: 'Search engines show the most dramatic or most-clicked results, not the most likely one for YOU. A common headache can surface scary results. The internet doesn\'t know your age, history, or the full picture — so it can\'t weigh what\'s actually probable.' },
      { type: 'heading', text: 'The Anxiety Spiral' },
      { type: 'paragraph', text: 'There\'s even a name for it — "cyberchondria": the anxiety that builds from searching symptoms. One search leads to another, each scarier, until a minor issue feels like an emergency. That stress can genuinely make you feel worse.' },
      { type: 'heading', text: 'When Online Info IS Useful' },
      { type: 'paragraph', text: 'Reading from trusted sources to understand a condition, prepare questions for your doctor, or learn general prevention is genuinely helpful. The problem is self-diagnosing and self-medicating based on it.' },
      { type: 'heading', text: 'A Calmer, Smarter Approach' },
      { type: 'paragraph', text: '• Note your actual symptoms — when they started, how bad, what makes them better/worse\n• Don\'t start medicines based on a search\n• For anything persistent, worsening, or worrying — ask a real doctor\n• Use online reading to prepare questions, not to conclude' },
      { type: 'heading', text: 'The 2 AM Fix' },
      { type: 'paragraph', text: 'Instead of spiralling through search results, you can now consult a real, verified doctor from home in a couple of minutes. A short conversation with someone who can actually assess you beats an hour of frightening search results — and gives you a clear, personalised answer and a plan.' },
      { type: 'heading', text: 'The Bottom Line' },
      { type: 'paragraph', text: 'Google is great for directions and recipes — not for diagnosing your body. When in doubt, ask a doctor. It\'s faster, calmer, and actually accurate.' },
    ]
  }
];
