// Blog articles — stored as static content
// Each article targets long-tail keywords for SEO

export const articles = [
  {
    slug: 'signs-you-should-see-a-dermatologist',
    title: '10 Signs You Should See a Dermatologist',
    description: 'Persistent acne, unusual moles, sudden hair loss? Learn the warning signs that mean you need a dermatologist consultation.',
    specialization: 'Dermatologist',
    publishedDate: '2026-08-01',
    readTime: '5 min',
    image: '🧴',
    content: [
      { type: 'intro', text: 'Your skin is your body\'s largest organ, and changes in it can signal underlying health issues. While minor skin concerns often resolve on their own, certain symptoms require professional attention. Here are 10 signs you should consult a dermatologist.' },
      { type: 'heading', text: '1. Persistent Acne That Won\'t Clear' },
      { type: 'paragraph', text: 'If over-the-counter products haven\'t helped after 2-3 months, a dermatologist can prescribe stronger treatments like retinoids, antibiotics, or hormonal therapy. Severe acne left untreated can cause permanent scarring.' },
      { type: 'heading', text: '2. Sudden or Excessive Hair Loss' },
      { type: 'paragraph', text: 'Losing 50-100 hairs daily is normal. But if you notice thinning patches, bald spots, or excessive shedding, it could indicate alopecia, thyroid issues, or nutritional deficiencies. Early treatment gives the best results.' },
      { type: 'heading', text: '3. A Mole That Changes Shape or Color' },
      { type: 'paragraph', text: 'Use the ABCDE rule: Asymmetry, Border irregularity, Color changes, Diameter larger than 6mm, or Evolving appearance. Any of these warrant immediate consultation to rule out skin cancer.' },
      { type: 'heading', text: '4. Rashes That Don\'t Go Away' },
      { type: 'paragraph', text: 'A rash lasting more than 2 weeks, spreading, or accompanied by fever needs medical attention. It could be eczema, psoriasis, fungal infection, or an allergic reaction.' },
      { type: 'heading', text: '5. Severe Itching Without Visible Cause' },
      { type: 'paragraph', text: 'Chronic itching (pruritus) without a rash can indicate liver problems, kidney disease, or internal conditions. A dermatologist can run tests to identify the cause.' },
      { type: 'heading', text: '6. Skin Infections That Keep Returning' },
      { type: 'paragraph', text: 'Recurring boils, fungal infections, or cold sores suggest an underlying immune issue. Professional treatment breaks the cycle of recurrence.' },
      { type: 'heading', text: '7. Excessive Sweating (Hyperhidrosis)' },
      { type: 'paragraph', text: 'If you sweat excessively even in cool conditions, prescription antiperspirants, Botox injections, or other treatments can help significantly.' },
      { type: 'heading', text: '8. Nail Changes' },
      { type: 'paragraph', text: 'Discoloration, thickening, or separation of nails can indicate fungal infections, psoriasis, or nutritional deficiencies. Don\'t ignore persistent nail problems.' },
      { type: 'heading', text: '9. Dark Patches or Pigmentation' },
      { type: 'paragraph', text: 'Melasma, dark circles, or uneven skin tone can be treated effectively with professional chemical peels, laser therapy, or topical prescriptions.' },
      { type: 'heading', text: '10. Chronic Dandruff or Scalp Issues' },
      { type: 'paragraph', text: 'Persistent dandruff that doesn\'t respond to medicated shampoos may be seborrheic dermatitis or scalp psoriasis, requiring prescription treatment.' },
      { type: 'heading', text: 'When to Book a Consultation' },
      { type: 'paragraph', text: 'Don\'t wait for skin problems to worsen. Early diagnosis and treatment prevents scarring, spreading, and complications. Most skin conditions are highly treatable when caught early.' },
    ]
  },
  {
    slug: 'when-to-visit-a-gynaecologist',
    title: 'When to Visit a Gynaecologist — Complete Guide',
    description: 'Irregular periods, pelvic pain, pregnancy planning? Know when you should consult a gynaecologist and what to expect during your visit.',
    specialization: 'Gynaecologist',
    publishedDate: '2026-08-02',
    readTime: '6 min',
    image: '🤰',
    content: [
      { type: 'intro', text: 'Many women delay gynaecologist visits due to embarrassment or uncertainty about when it\'s necessary. Regular check-ups and timely consultations are crucial for reproductive health. Here\'s your complete guide.' },
      { type: 'heading', text: 'You Should Visit a Gynaecologist If You Have:' },
      { type: 'paragraph', text: '• Irregular, heavy, or painful periods\n• Missed periods (when not pregnant)\n• Unusual vaginal discharge or odor\n• Pelvic pain or pressure\n• Pain during intercourse\n• Planning pregnancy or need contraception advice\n• Reached age 21 (routine screening recommended)' },
      { type: 'heading', text: 'Common Conditions a Gynaecologist Treats' },
      { type: 'paragraph', text: 'PCOD/PCOS is one of the most common conditions affecting Indian women, causing irregular periods, weight gain, acne, and fertility issues. Early management with lifestyle changes and medication can prevent complications.' },
      { type: 'paragraph', text: 'Endometriosis affects 1 in 10 women and causes severe period pain, heavy bleeding, and fertility problems. Many women suffer for years before diagnosis — don\'t normalize extreme pain.' },
      { type: 'paragraph', text: 'Fibroids are non-cancerous growths in the uterus that can cause heavy periods, pelvic pressure, and frequent urination. Treatment ranges from medication to minimally invasive procedures.' },
      { type: 'heading', text: 'Pregnancy and Prenatal Care' },
      { type: 'paragraph', text: 'If you\'re planning pregnancy, a pre-conception visit helps identify and address any issues beforehand. Once pregnant, regular antenatal visits monitor both mother and baby\'s health.' },
      { type: 'heading', text: 'What to Expect During Your Visit' },
      { type: 'paragraph', text: 'A typical visit includes discussion of your symptoms, medical history, and possibly a physical examination. Many concerns can be addressed through consultation alone — not every visit requires an examination.' },
      { type: 'heading', text: 'Can You Consult Online?' },
      { type: 'paragraph', text: 'Yes! Many gynaecological concerns — period problems, PCOD management, contraception advice, pregnancy queries — can be effectively addressed through video consultation. Physical examination is only needed for specific cases.' },
    ]
  },
  {
    slug: 'heart-attack-warning-signs',
    title: 'Heart Attack Warning Signs — When to See a Cardiologist',
    description: 'Chest pain, breathlessness, high BP? Learn the warning signs of heart disease and when you should consult a cardiologist immediately.',
    specialization: 'Cardiologist',
    publishedDate: '2026-08-03',
    readTime: '5 min',
    image: '❤️',
    content: [
      { type: 'intro', text: 'Heart disease is the #1 killer in India, causing over 25% of all deaths. Many heart attacks happen to people who ignored warning signs for months. Know when to see a cardiologist — it could save your life.' },
      { type: 'heading', text: 'Emergency Signs — Go to Hospital Immediately' },
      { type: 'paragraph', text: '• Crushing chest pain or pressure lasting more than 5 minutes\n• Pain spreading to left arm, jaw, neck, or back\n• Severe breathlessness with sweating\n• Sudden dizziness or fainting\n• Nausea with chest discomfort\n\nCall an ambulance immediately. Do NOT drive yourself.' },
      { type: 'heading', text: 'Warning Signs — Book a Cardiologist Appointment' },
      { type: 'paragraph', text: '• Blood pressure consistently above 140/90\n• Chest pain or tightness during physical activity\n• Shortness of breath climbing stairs\n• Irregular heartbeat or palpitations\n• Swelling in legs, ankles, or feet\n• Unexplained fatigue\n• Family history of heart disease' },
      { type: 'heading', text: 'Risk Factors You Can Control' },
      { type: 'paragraph', text: 'High blood pressure, diabetes, smoking, obesity, lack of exercise, high cholesterol, and stress all increase heart disease risk. A cardiologist can create a prevention plan tailored to your risk factors.' },
      { type: 'heading', text: 'Tests a Cardiologist May Recommend' },
      { type: 'paragraph', text: 'ECG (electrocardiogram), echocardiogram, stress test, lipid profile, and cardiac CT scan help assess heart health. Many are non-invasive and quick.' },
      { type: 'heading', text: 'Prevention is Better Than Cure' },
      { type: 'paragraph', text: 'If you\'re over 35, have diabetes or high BP, or have a family history of heart disease — schedule a preventive cardiologist consultation. Early intervention saves lives.' },
    ]
  },
  {
    slug: 'child-sick-when-to-see-pediatrician',
    title: 'Is Your Child Sick? When to Take Them to a Pediatrician',
    description: 'Fever, cough, rashes in children — know when home remedies are enough and when you need a pediatrician consultation.',
    specialization: 'Pediatrician',
    publishedDate: '2026-08-04',
    readTime: '5 min',
    image: '👶',
    content: [
      { type: 'intro', text: 'Every parent worries when their child falls sick. While most childhood illnesses are minor and resolve on their own, certain signs indicate you should consult a pediatrician promptly. Here\'s your guide to knowing the difference.' },
      { type: 'heading', text: 'See a Pediatrician Immediately If Your Child Has:' },
      { type: 'paragraph', text: '• Fever above 102°F (39°C) lasting more than 2 days\n• Difficulty breathing or rapid breathing\n• Refusing to eat or drink for more than 12 hours\n• Severe vomiting or diarrhea (risk of dehydration)\n• Rash that doesn\'t fade when pressed\n• Unusual drowsiness or difficulty waking\n• Seizures or convulsions' },
      { type: 'heading', text: 'Common Childhood Illnesses That Need a Doctor' },
      { type: 'paragraph', text: 'Ear infections (pulling at ears, crying), urinary tract infections (pain during urination, fever), and respiratory infections (persistent cough, wheezing) all need professional treatment — home remedies aren\'t enough.' },
      { type: 'heading', text: 'Routine Pediatrician Visits' },
      { type: 'paragraph', text: 'Even when your child is healthy, regular check-ups are important:\n• Monthly for first year\n• Every 3 months (ages 1-3)\n• Every 6 months (ages 3-6)\n• Annually after age 6\n\nThese visits track growth, development milestones, and vaccinations.' },
      { type: 'heading', text: 'Vaccination Schedule' },
      { type: 'paragraph', text: 'Following India\'s National Immunization Schedule protects your child from serious diseases. Missed a vaccine? A pediatrician can create a catch-up schedule.' },
      { type: 'heading', text: 'Online Pediatric Consultation' },
      { type: 'paragraph', text: 'For non-emergency concerns — mild fever, feeding issues, minor rashes, behavioral questions — video consultation with a pediatrician is convenient and effective. You get professional advice without exposing a sick child to more germs in a waiting room.' },
    ]
  },
  {
    slug: 'mental-health-when-to-get-help',
    title: 'Mental Health: 7 Signs You Need Professional Help',
    description: 'Depression, anxiety, insomnia — when should you see a psychiatrist? Learn the signs that indicate you need professional mental health support.',
    specialization: 'Psychiatrist',
    publishedDate: '2026-08-05',
    readTime: '5 min',
    image: '🧠',
    content: [
      { type: 'intro', text: 'Mental health is as important as physical health, yet most Indians hesitate to seek help. There\'s no shame in consulting a psychiatrist — it\'s a sign of strength, not weakness. Here are 7 signs you should reach out.' },
      { type: 'heading', text: '1. Persistent Sadness or Hopelessness' },
      { type: 'paragraph', text: 'Feeling sad for more than 2 weeks, losing interest in activities you once enjoyed, or feeling empty and hopeless are classic signs of depression. It\'s a medical condition, not a character flaw — and it\'s treatable.' },
      { type: 'heading', text: '2. Overwhelming Anxiety or Worry' },
      { type: 'paragraph', text: 'If worry dominates your daily life, causes physical symptoms (racing heart, sweating, nausea), or prevents you from normal activities, professional help can make a dramatic difference.' },
      { type: 'heading', text: '3. Sleep Problems' },
      { type: 'paragraph', text: 'Chronic insomnia (can\'t fall asleep) or hypersomnia (sleeping too much) lasting more than 3 weeks often indicates an underlying mental health condition that needs treatment.' },
      { type: 'heading', text: '4. Panic Attacks' },
      { type: 'paragraph', text: 'Sudden episodes of intense fear with physical symptoms — chest pain, difficulty breathing, dizziness, trembling — are panic attacks. They\'re terrifying but highly treatable with the right approach.' },
      { type: 'heading', text: '5. Relationship or Work Problems' },
      { type: 'paragraph', text: 'When mental health issues start affecting your relationships, work performance, or daily functioning, it\'s time to seek help before things deteriorate further.' },
      { type: 'heading', text: '6. Substance Use to Cope' },
      { type: 'paragraph', text: 'Using alcohol, drugs, or medications to manage stress, anxiety, or emotional pain is a warning sign. A psychiatrist can address the root cause and provide healthier coping strategies.' },
      { type: 'heading', text: '7. Thoughts of Self-Harm' },
      { type: 'paragraph', text: 'If you\'re having thoughts of hurting yourself or ending your life, please reach out immediately. Call a helpline (Vandrevala Foundation: 1860-2662-345) or consult a psychiatrist urgently. Help is available.' },
      { type: 'heading', text: 'Online Mental Health Consultation' },
      { type: 'paragraph', text: 'Mental health consultations are particularly effective online — you can speak from the privacy of your home, without the stigma of visiting a clinic. Video calls offer the same quality of care as in-person visits for therapy and medication management.' },
    ]
  },
  {
    slug: 'back-pain-when-to-see-orthopedic',
    title: 'Back Pain: When to See an Orthopedic Doctor',
    description: 'Is your back pain serious? Learn when home remedies aren\'t enough and you need an orthopedic specialist for back, knee, or joint pain.',
    specialization: 'Orthopedic',
    publishedDate: '2026-08-06',
    readTime: '5 min',
    image: '🦴',
    content: [
      { type: 'intro', text: 'Back pain affects 80% of people at some point in their lives. While most episodes resolve within a few weeks, certain signs indicate you need professional orthopedic care. Ignoring serious back problems can lead to permanent nerve damage.' },
      { type: 'heading', text: 'See an Orthopedic Doctor Immediately If:' },
      { type: 'paragraph', text: '• Pain radiates down your leg (sciatica)\n• Numbness or tingling in legs or feet\n• Loss of bladder or bowel control\n• Pain after a fall or accident\n• Pain that worsens at night\n• Back pain with fever (possible infection)' },
      { type: 'heading', text: 'Common Causes of Back Pain' },
      { type: 'paragraph', text: 'Muscle strain is the most common cause — from lifting heavy objects, sudden movements, or poor posture. This usually heals in 2-4 weeks with rest and pain medication.' },
      { type: 'paragraph', text: 'Slip disc (herniated disc) occurs when the soft cushion between vertebrae bulges out and presses on nerves. Symptoms include shooting pain, numbness, and weakness in legs.' },
      { type: 'paragraph', text: 'Spondylosis is age-related wear of the spine. It\'s common after age 40 and causes stiffness and pain, especially in the morning.' },
      { type: 'heading', text: 'Do I Need Surgery?' },
      { type: 'paragraph', text: 'Good news: 90% of back problems are treated WITHOUT surgery. Treatment options include physiotherapy, pain medication, spinal injections, and lifestyle modifications. Surgery is only considered when conservative treatment fails after 6-12 weeks.' },
      { type: 'heading', text: 'Prevention Tips' },
      { type: 'paragraph', text: '• Maintain good posture while sitting and standing\n• Exercise regularly (even 30 minutes of walking helps)\n• Strengthen core muscles\n• Lift heavy objects with your knees, not your back\n• Take breaks if you sit for long hours\n• Maintain a healthy weight' },
      { type: 'heading', text: 'Online Orthopedic Consultation' },
      { type: 'paragraph', text: 'Many back problems can be initially assessed online. The doctor can evaluate your symptoms, recommend imaging (X-ray/MRI), prescribe medication, and suggest exercises — all through video consultation. In-person visits are needed only for physical examination or procedures.' },
    ]
  },
  {
    slug: 'dental-problems-complete-guide',
    title: 'Common Dental Problems and When to See a Dentist',
    description: 'Toothache, bleeding gums, bad breath? Learn about common dental issues and when you should visit a dentist before it gets worse.',
    specialization: 'Dentist',
    publishedDate: '2026-08-07',
    readTime: '5 min',
    image: '🦷',
    content: [
      { type: 'intro', text: 'Dental problems are among the most common health issues in India, yet many people avoid the dentist until pain becomes unbearable. Early treatment is simpler, cheaper, and less painful. Here\'s what you need to know.' },
      { type: 'heading', text: 'See a Dentist Urgently If You Have:' },
      { type: 'paragraph', text: '• Severe toothache that doesn\'t respond to painkillers\n• Swelling in the face or jaw\n• Bleeding that won\'t stop after tooth extraction\n• A knocked-out or broken tooth\n• Pus or abscess near a tooth\n• Difficulty opening your mouth' },
      { type: 'heading', text: 'Common Problems You Shouldn\'t Ignore' },
      { type: 'paragraph', text: 'Cavities start small and painless but grow until they reach the nerve, causing severe pain. A small filling costs ₹500-1000 — a root canal for an ignored cavity costs ₹5000-10000. Don\'t wait.' },
      { type: 'paragraph', text: 'Bleeding gums while brushing is NOT normal. It\'s usually gingivitis (gum inflammation) which, untreated, progresses to periodontitis — causing tooth loss. Professional cleaning reverses early gum disease.' },
      { type: 'paragraph', text: 'Persistent bad breath despite good oral hygiene can indicate gum disease, infected teeth, or other health issues. A dentist can identify the exact cause.' },
      { type: 'heading', text: 'How Often Should You Visit?' },
      { type: 'paragraph', text: 'Every 6 months for a routine check-up and cleaning — even if you have no pain. Many dental problems are painless in early stages and only a dentist can detect them.' },
      { type: 'heading', text: 'Modern Dentistry is Painless' },
      { type: 'paragraph', text: 'Worried about pain? Modern anesthesia makes most procedures painless. Laser dentistry, painless injections, and sedation options mean you can get treated comfortably.' },
      { type: 'heading', text: 'Online Dental Consultation' },
      { type: 'paragraph', text: 'While procedures require in-person visits, initial consultation — assessing your problem, prescribing pain relief, recommending treatment options — can be done online. Share photos of the affected area during a video call.' },
    ]
  },
  {
    slug: 'eye-problems-vision-care-guide',
    title: 'Eye Problems: When to See an Ophthalmologist',
    description: 'Blurry vision, eye strain, headaches? Know when common eye problems need professional attention from an ophthalmologist.',
    specialization: 'Ophthalmologist',
    publishedDate: '2026-08-08',
    readTime: '5 min',
    image: '👁️',
    content: [
      { type: 'intro', text: 'Your eyes work harder than almost any organ — processing millions of pieces of information daily. With increasing screen time, eye problems are rising rapidly in India. Here\'s when you should see an ophthalmologist.' },
      { type: 'heading', text: 'Emergency — See a Doctor Immediately:' },
      { type: 'paragraph', text: '• Sudden vision loss in one or both eyes\n• Flash of light followed by floating spots\n• Eye injury (chemical splash, foreign object)\n• Sudden severe eye pain with nausea\n• Red eye with vision changes' },
      { type: 'heading', text: 'Book an Appointment If You Notice:' },
      { type: 'paragraph', text: '• Difficulty reading or seeing distant objects\n• Frequent headaches related to vision\n• Eye strain from computers/phones\n• Dry, itchy, or watery eyes\n• Difficulty seeing at night\n• Double vision\n• Gradual change in color perception' },
      { type: 'heading', text: 'Common Eye Conditions' },
      { type: 'paragraph', text: 'Myopia (near-sightedness) is epidemic among young Indians — affecting over 30% of urban children. Early intervention with proper glasses prevents progression.' },
      { type: 'paragraph', text: 'Digital eye strain (computer vision syndrome) affects anyone spending 3+ hours on screens daily. Symptoms include headaches, dry eyes, and blurred vision. The 20-20-20 rule helps: every 20 minutes, look at something 20 feet away for 20 seconds.' },
      { type: 'paragraph', text: 'Cataracts are the leading cause of blindness in India but are 100% treatable with a simple 15-minute surgery. If your vision is getting cloudy or yellowish, get checked.' },
      { type: 'heading', text: 'Routine Eye Exams' },
      { type: 'paragraph', text: '• Children: first exam at age 3, then before starting school\n• Adults (20-39): every 5 years if no issues\n• Adults (40-54): every 2-4 years\n• Adults (55+): every 1-3 years\n• Diabetics: annually regardless of age' },
      { type: 'heading', text: 'Protecting Your Eyes Daily' },
      { type: 'paragraph', text: '• Follow the 20-20-20 rule for screen use\n• Wear UV-protective sunglasses outdoors\n• Eat green vegetables and omega-3 rich foods\n• Don\'t rub your eyes with dirty hands\n• Use proper lighting while reading\n• Get adequate sleep (7-8 hours)' },
    ]
  },
  {
    slug: 'stomach-problems-gastroenterologist',
    title: 'Stomach Problems: When to Consult a Gastroenterologist',
    description: 'Acidity, bloating, constipation? Learn when digestive problems need a gastroenterologist and what conditions they treat.',
    specialization: 'Gastroenterologist',
    publishedDate: '2026-08-09',
    readTime: '5 min',
    image: '🤢',
    content: [
      { type: 'intro', text: 'Digestive problems are incredibly common in India — from acidity and bloating to more serious conditions like IBS and liver disease. While occasional stomach issues are normal, persistent symptoms need professional evaluation.' },
      { type: 'heading', text: 'See a Gastroenterologist If You Experience:' },
      { type: 'paragraph', text: '• Acidity/heartburn more than twice a week\n• Blood in stool or black-colored stools\n• Unexplained weight loss\n• Persistent abdominal pain\n• Difficulty swallowing\n• Chronic diarrhea or constipation (>3 weeks)\n• Jaundice (yellowing of skin/eyes)\n• Bloating that doesn\'t improve with diet changes' },
      { type: 'heading', text: 'Common Conditions' },
      { type: 'paragraph', text: 'GERD (acid reflux) affects millions. While antacids provide temporary relief, chronic GERD can damage the food pipe. A gastroenterologist provides long-term solutions beyond over-the-counter medication.' },
      { type: 'paragraph', text: 'IBS (Irritable Bowel Syndrome) causes alternating constipation and diarrhea, bloating, and cramps. It\'s manageable with the right diet, medication, and stress management — but needs proper diagnosis first.' },
      { type: 'paragraph', text: 'Fatty liver disease is silently affecting 30-40% of urban Indians. Often discovered accidentally during tests, untreated fatty liver can progress to liver failure. Lifestyle changes can reverse it if caught early.' },
      { type: 'heading', text: 'When Stomach Problems Are Serious' },
      { type: 'paragraph', text: 'Most stomach issues are benign, but these signs need urgent attention:\n• Blood in vomit or stool\n• Sudden severe abdominal pain\n• High fever with abdominal pain\n• Inability to keep any food/water down for 24 hours\n• Significant unexplained weight loss' },
      { type: 'heading', text: 'Lifestyle Changes That Help' },
      { type: 'paragraph', text: '• Eat smaller, more frequent meals\n• Avoid spicy, oily food late at night\n• Don\'t lie down within 2 hours of eating\n• Reduce stress (yoga, meditation help)\n• Stay hydrated\n• Include fiber in your diet\n• Limit alcohol and caffeine' },
      { type: 'heading', text: 'Online Consultation for Digestive Issues' },
      { type: 'paragraph', text: 'Gastroenterology consultations work well online — the doctor can assess symptoms, review test reports, prescribe medication, and recommend dietary changes through video call. Procedures like endoscopy require in-person visits.' },
    ]
  },
  {
    slug: 'diabetes-thyroid-endocrinologist',
    title: 'Diabetes and Thyroid: When to See an Endocrinologist',
    description: 'Managing diabetes, thyroid disorders, or hormonal imbalances? Learn when you need an endocrinologist and what they treat.',
    specialization: 'Endocrinologist',
    publishedDate: '2026-08-10',
    readTime: '5 min',
    image: '💉',
    content: [
      { type: 'intro', text: 'India is the diabetes capital of the world with over 77 million diabetics. Thyroid disorders affect 1 in 10 Indians. These hormonal conditions need specialist care — not just a general physician. Here\'s when to see an endocrinologist.' },
      { type: 'heading', text: 'See an Endocrinologist If:' },
      { type: 'paragraph', text: '• Your diabetes isn\'t controlled despite medication\n• You need insulin management\n• You have diabetes complications (kidney, eye, nerve problems)\n• Thyroid medication isn\'t working well\n• You have PCOD with hormonal imbalance\n• Unexplained weight gain or loss\n• Fatigue, mood swings, or irregular periods\n• Calcium or vitamin D deficiency not responding to supplements' },
      { type: 'heading', text: 'Diabetes — More Than Just Sugar Control' },
      { type: 'paragraph', text: 'Type 2 diabetes is progressive — what works today may not work in 5 years. An endocrinologist adjusts your treatment plan over time, monitors complications, and helps prevent heart disease, kidney failure, and nerve damage.' },
      { type: 'paragraph', text: 'If your HbA1c is above 7% despite medication, or you\'re experiencing numbness in feet, vision changes, or frequent infections — you need specialist care urgently.' },
      { type: 'heading', text: 'Thyroid Disorders' },
      { type: 'paragraph', text: 'Hypothyroidism (low thyroid) causes fatigue, weight gain, cold intolerance, and depression. Hyperthyroidism (overactive thyroid) causes weight loss, anxiety, tremors, and rapid heartbeat. Both need proper dosage management by a specialist.' },
      { type: 'paragraph', text: 'Thyroid nodules and goiter need evaluation to rule out cancer. Most are benign but should be monitored regularly.' },
      { type: 'heading', text: 'PCOD and Hormonal Issues' },
      { type: 'paragraph', text: 'PCOD involves insulin resistance, high androgens, and metabolic issues that go beyond just irregular periods. An endocrinologist addresses the metabolic root cause — not just the symptoms.' },
      { type: 'heading', text: 'Online Endocrinology Consultation' },
      { type: 'paragraph', text: 'Endocrinology is ideal for online consultations — most follow-ups involve reviewing blood reports, adjusting medication doses, and discussing lifestyle changes. Share your lab reports during a video call and get expert advice from anywhere in India.' },
    ]
  }
];
